version: '2'
services:
    nginx:
        build: ./docker/nginx
        volumes:
            - ./application:/var/www
        networks:
            - app_network
        ports:
            - "80:80"

    nodejs:
        build: ./docker/nodejs
        volumes:
            - ./application:/var/www
        networks:
            - app_network
        ports:
            - "3000:3000"

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - data:/var/lib/mysql
        networks:
            - app_network

    workspace:
        build: ./docker/workspace
        volumes:
            - ./application:/var/www
        tty: true

networks:
    app_network:
        driver: 'bridge'
volumes:
    data:
        driver: 'local'